name: Dispatch Listener

on:
  repository_dispatch:
    types: [trigger_save]

jobs:
  update-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update trigger.txt
        run: |
          echo "Save triggered at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > trigger.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add trigger.txt
          git commit -m "Triggered save from HTML"
          git push
        env:
          YOUR_PAT: ${{ secrets.YOUR_PAT }}

