name: Dispatch Listener

on:
  repository_dispatch:
    types: [trigger-action, updateHtml, save-html]

jobs:
  listener:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo "✅ Git user configured"

      - name: Confirm GH_PAT Presence
        run: |
          echo "${GH_PAT}" | grep -E "^gh[pus]_"
          if [ $? -ne 0 ]; then
            echo "❌ GH_PAT looks empty or malformed"
            exit 1
          fi
          echo "✅ GH_PAT appears valid"

      - name: Update trigger.txt (force commit)
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Save triggered at $timestamp - $RANDOM" > trigger.txt
          git add trigger.txt
          git status
          git diff



      - name: Commit Changes
        run: |
          git commit -m "Triggered save from HTML"
          echo "✅ Commit created"

      - name: Push Changes to GitHub
        run: |
          git remote -v
          git push --verbose https://x-access-token:${GH_PAT}@github.com/RogueShadowTech/RST-AntLegion-ONE.git
