name: Dispatch Listener

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  listener:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.YOUR_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Trigger commit
        run: |
          echo "$(date)" >> trigger.txt
          git add trigger.txt
          git commit -m "Triggered save from HTML"
          git push https://x-access-token:${GH_PAT}@github.com/RogueShadowTech/RST-AntLegion-ONE.git


