name: Dispatch Listener

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  listener:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.YOUR_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          echo "✅ Git configured"

      - name: Verify token
        run: |
          echo "${GH_PAT}" | grep -E "^gh[pus]_"
          if [ $? -ne 0 ]; then
            echo "❌ GH_PAT is missing or invalid"
            exit 1
          fi

      - name: Force trigger.txt update
        run: |
          echo "$(date) - $RANDOM" >> trigger.txt
          git add trigger.txt
          git status
          git diff

      - name: Commit changes
        run: |
          git commit -m "Triggered update from dispatch"
          echo "✅ Commit complete"

      - name: Push to GitHub
        run: |
          git remote -v
          git push --verbose https://x-access-token:${GH_PAT}@github.com/RogueShadowTech/RST-AntLegion-ONE.git


